# Generated by Django 3.0.5 on 2020-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='company_name',
            field=models.CharField(default='Rightbros', max_length=255),
            preserve_default=False,
        ),
    ]
