# Generated by Django 3.0.5 on 2020-04-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seller_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
